version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - WeatherApiKey=${WeatherApiKey} # This is the environment variable that is used in the API to access the weather API
    networks:
      - skystatus-network

  client:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - skystatus-network
    environment:
      - REACT_APP_API_URL=http://api:5000
      - PORT=80

networks:
  skystatus-network:
    driver: bridge
