version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - bluetreadweather-network

  client:
    build:
      context: client
    ports:
      - "3000:80"
    networks:
      - bluetreadweather-network

networks:
  bluetreadweather-network:
    driver: bridge
