version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - WeatherApiKey=0fea47bd033f4d768d3182340230504
    networks:
      - bluetreadweather-network

  client:
    build:
      context: client
    ports:
      - "3000:80"
    networks:
      - bluetreadweather-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

networks:
  bluetreadweather-network:
    driver: bridge
